<?php  
	$str = "Apple lab";
	$rslt = addslashes($str);
	echo $str."<br>";
	echo "$rslt";
	echo "<br>"."<br>"."<br>";
	$str1 = "Nissan, Skoda, Audi, Hyundai";
	$rslt1 = explode(',', $str1);
	echo "<pre>";
	print_r($rslt1);
	echo "<br>"."<br>"."<br>";
	$str2 = "Hello world, how are you?";
	$rslt2 = explode(' ', $str2);
	echo "<pre>";
	print_r($rslt2);
	echo "<br>"."<br>"."<br>";
	$implode = implode(' ', $rslt1);
	echo $implode, "<br><br>";
	print_r($rslt1);
	echo "<br>"."<br>"."<br>";
	echo strpos("Hello how are you? fine? thankyou.", "fine?");
	echo "<br>"."<br>"."<br>";
	echo strlen("Heloooo");
	echo "<br>"."<br>"."<br>";
	echo stripos("Hello how are you? fine? thankyou.", "fine?");
	echo "<br>"."<br>"."<br>";
	echo strrpos("Hello how are you? fine? thankyou.", "fine?");
	$htmlentity = "<hr><hr>";
	htmlentities($htmlentity);
	echo $htmlentity;
	echo "<br>"."<br>"."<br>";
	html_entity_decode($htmlentity);
	echo $htmlentity;
	echo "<br>"."<br>"."<br>";
	$text = "This is a nice text";
	echo lcfirst($text);
	echo "<br>"."<br>"."<br>";
	echo ucfirst($text);
	echo "<br>"."<br>"."<br>";
	echo ucwords($text);
	echo "<br>"."<br>"."<br>";
	echo md5($text);
	echo "<br>"."<br>"."<br>";
	echo sha1($text);
	echo "<br>"."<br>"."<br>";
	echo ltrim($text);
	echo "<br>"."<br>"."<br>";
	echo rtrim($text);
	echo "<br>"."<br>"."<br>";
	echo trim($text);
	echo "<br>"."<br>"."<br>";
	$rtext1 = "Hello.";
	$rtext2 = "Good morning.";
	echo str_replace("Good", $rtext1, $rtext2);
	echo "<br>"."<br>"."<br>";
	$amount = 1000;
	$nformat = number_format($amount, 2);
	echo $nformat;
?>